apiVersion: v1
kind: Secret
metadata:
  name: resr-secret
type: Opaque
stringData:
  ASPNETCORE_ENVIRONMENT: "Development"
  Root__Email: "root@resr.fr"
  Root__Password: "abcdABCD1234"
  DB__Host: "postgres"
  DB__Port: "5432"
  DB__Database: "resr"
  DB__Username: "root@resr.fr"
  DB__Password: "abcdABCD1234"
  DB__EncryptionKey: "CPLYsGwJf0p2=P01DHBM&t2=iiIL+tp)"
  Jwt__Key: "89146b8ddf1048189ffaad64b1e402eacfaf96f055008e4efcfeca40dd8e38f2715c20f06a2b1703e3717f303b59c0ba4921fd3ff67658c6f7ef89003fbe29"
  Jwt__Issuer: "resr.fr"
  Jwt__Audience: "resr.fr"
  Jwt__Expiry__Manager: "00:15"
  Jwt__Expiry__User: "01:00"
  Pin__RegistrationValidationRequestExpiry: "00:10"
  Pin__PasswordResetRequestExpiry: "00:10"
  Smtp__Host: "maildev"
  Smtp__Port: "1025"
  Smtp__SenderEmail: "noreply@resr.fr"
  Serilog__MinimumLevel__Default: "Information"
  Serilog__MinimumLevel__Override__System: "Warning"
  Serilog__MinimumLevel__Override__Microsoft: "Warning"
  Serilog__MinimumLevel__Override__Microsoft.Hosting.Lifetime: "Warning"
  Serilog__MinimumLevel__Override__Microsoft.EntityFrameworkCore: "Warning"
  Serilog__MinimumLevel__Override__Microsoft.AspNetCore.DataProtection: "Error"
  Serilog__MinimumLevel__Override__Serilog.AspNetCore.RequestLoggingMiddleware: "Fatal"